version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=cursos
      # Si quieres añadir autenticación, descomenta las siguientes líneas
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db  # Volumen persistente  

  solr:
    image: solr:8.11.4
    container_name: solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cursos
    networks:
      - app-network

  memcached:
    image: memcached:1.6
    container_name: memcached
    ports:
      - "11212:11211"
    networks:
      - app-network

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile  # Si tienes un Dockerfile específico
    container_name: users-api
    environment:
      SECRET_KEY: "Pirata02"            # Cambiar por una clave más segura en producción
      DB_HOST: mysql                    # Verifica que el nombre del servicio sea correcto
      DB_USER: root                     # Actualizado al usuario que realmente usas en MySQL
      DB_PASSWORD: root                 # Actualizado a la contraseña correcta de MySQL
      DB_NAME: arqsoft2                 # Asegúrate de que coincide con la base de datos creada
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    ports:
      - "8082:8080"                    # Mapeo correcto del puerto
    depends_on:
      mysql:
        condition: service_healthy     # Se asegura de que MySQL esté listo antes de levantar `users-api`
      memcached:
        condition: service_started
    networks:
      - app-network                    # Verifica que `app-network` esté definido en `docker-compose.yml`
    restart: unless-stopped            # Reinicia automáticamente si el contenedor falla


  cursos-api:
    build:
      context: ./cursos-api
    container_name: cursos-api
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=arqsoft2
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"  
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "./cursos-api"]

  search-api:
    build:
      context: ./search-api
    container_name: search-api
    environment:
      RABBITMQ_HOST: rabbitmq
      SOLR_HOST: solr
    ports:
      - "8083:8080"  
    depends_on:
      rabbitmq:
        condition: service_started
      solr:
        condition: service_started
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-t", "30", "--", "./search-api"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - users-api
      - cursos-api
      - search-api
    networks:
      - app-network

volumes:
  mysql-data:
  mongodb_data:

networks:
  app-network:
    driver: bridge